# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jessica Moloney
tagline: 'Hello'
email: you-email@example.com
description: "" # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jmmoloney.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jmmoloney

hydeout:
  repo: "https://github.com/jmmoloney"
  linkedin: "https://www.linkedin.com/in/jessicamoloney/"

remote_theme: jmmoloney/hydeout@profile_pic
# sass:
#   sass_dir: assets/css

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /blog/:year/:month/:day/:title

disqus:
  shortname:
# theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate

sidebar_home_link:  true
# sidebar_blog_link:  '/blog'
paginate: 5
# paginate_path:    '/blog/page:num'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
